### ISSUE TITLE
老哥 怎么知道输入框是聚焦还是失焦？

### ISSUE THREAD

**Issue by showtan001** [zjjjjjjjjjjd/react-native-scaninput#4]
![image](https://user-images.githubusercontent.com/32892347/150058117-a02c1fc9-248c-4efa-8290-fff83990d280.png)
![image](https://user-images.githubusercontent.com/32892347/150058154-63c48ba8-c034-487b-8a21-ad1e71ed2ae8.png)

都没有打印

**Comment by zjjjjjjjjjjd** [comment]
监听方法没写额，focus和blur是调用方法不是监听的

**Comment by showtan001** [comment]
@zjjjjjjjjjjd 能不能写个？

**Comment by zjjjjjjjjjjd** [comment]
我抽空看看，好久没写rn了

**Comment by zjjjjjjjjjjd** [comment]
不过目前你可以先用变量记录状态

**Comment by showtan001** [comment]
怎么个记录法？ 主要聚焦失焦状态不知道怎么获取

**Comment by showtan001** [comment]
我用点击来记录状态，谢谢老哥
